### ISSUE TITLE
Update manager offers me to update to older kernel version

### ISSUE THREAD

**Issue by AXDOOMER** [linuxmint/mintupdate#108]
I have installed Kernel version 4.0.4 in my computer, but the update manager offers me to update to  3.13.0-55.94. The update level is [5]. It doesn't show up when my system is up to date, but I see it when I have other updates to install or while the update manager is being refreshed. 

I have updated from Linux Mint 17.1 to 17.2. The recommended Kernel in this new version is 3.16.0-38.
I think it also suggested me to update to the older Kernel when I was using version 17.1. 

When I press "Refresh". 
![screenshot from 2015-06-20 14 53 32](https://cloud.githubusercontent.com/assets/6194072/8268756/c5818308-175c-11e5-826e-f7e12b8bc50d.png)

My installed Kernel. If I had some updates to install, it would show the older Kernel that it wants me to install like in the image above. 
![screenshot from 2015-06-20 14 54 35](https://cloud.githubusercontent.com/assets/6194072/8268758/d01c1972-175c-11e5-8a3a-ca50eeeb0ae1.png)

**Comment by Piiit** [comment]
Hi, I wanted to file the same bug report for LM18. I had installed kernel version 4.4.0-34 once, but removed it via the GUI "Kernels". It does not offer the oldest installed kernel, nor the recommended one. It offers always the last active from the repositories which got some updates, I guess. 
Tried to use `sudo apt purge linux-headers-4.4.0-34-generic` with no success.

Here is what I get:
![auswahl_031](https://cloud.githubusercontent.com/assets/6096063/18283861/a6910748-7467-11e6-9049-9fdaad233f88.jpg)

**Comment by lursel** [comment]
I'm having the same issue. Linux Mint 18. I've circumvented the annoyance by disabling kernel updates altogether, with the obvious drawback that I have to check manually.
![screenshot from 2016-12-06 16-18-47](https://cloud.githubusercontent.com/assets/16182390/20933504/2d155a26-bbd0-11e6-851f-6b0d2841a8cc.png)

**Comment by nickvergessen** [comment]
Had the same issue, the following helped:
```
apt-get remove linux-headers-4.4.0-*
```
afterwards only updates for 4.8 were suggested

**Comment by clefebvre** [comment]
Fixed on master today.

**Comment by CottonEaster** [comment]
Has the fix for this made it out to users yet, please? For I still have this problem (though I am trying the fix suggested above).
